[package]
name = "mercator"
version = "0.1.0"
entrypoint = "mercator.typ"
authors = ["Bernstein <https://gitea.tfnux.org/bernstein/> <https://github.com/bernsteining>"]
license = "Unlicense"
description = "Render GeoJSON in typst."
repository = "https://gitea.tfnux.org/bernstein/mercator/"
keywords = ["geojson", "map", "cartography", "vector tiles", "GIS"]
compiler = "0.8.0"